"""책(Book) 엔터티"""
type Book {
  _id: ID!

  """다국어 제목 (예: { "ko": "수학", "en": "Math" })"""
  title(language: String!): String!

  """저자 목록"""
  authors: [String!]!

  """출판사 이름 (선택)"""
  publisher: String

  """출판 연도 (선택)"""
  publishedYear: Int

  """ISBN 코드 (선택)"""
  isbn: String

  """분류 태그"""
  tags: [String!]!

  """S3 URL 배열 (페이지별 스캔된 이미지 주소)"""
  sourceFiles: [String!]!

  """연결된 토픽 ID 목록"""
  topicIds: [ID!]!

  """서버에서 동적으로 반환되는 Presigned URL 목록"""
  signedUrls: [String!]!

  """생성 일시"""
  createdAt: String!
}

"""책 생성 입력"""
input CreateBookInput {
  """다국어 제목 (예: { "ko": "수학", "en": "Math" })"""
  title: JSON!

  """저자 목록"""
  authors: [String!]

  """출판사 이름"""
  publisher: String

  """출판 연도"""
  publishedYear: Int

  """ISBN 코드"""
  isbn: String

  """분류 태그"""
  tags: [String!]

  """S3 파일 URL 목록 (페이지별 스캔된 이미지 주소)"""
  sourceFiles: [String!]!

  """연결된 토픽 ID 목록"""
  topicIds: [ID!]
}

"""책 수정 입력"""
input UpdateBookInput {
  """수정할 책 ID"""
  id: ID!

  """다국어 제목"""
  title: JSON

  """저자 목록"""
  authors: [String!]

  """출판사 이름"""
  publisher: String

  """출판 연도"""
  publishedYear: Int

  """ISBN 코드"""
  isbn: String

  """분류 태그"""
  tags: [String!]

  """S3 파일 URL 목록 (페이지별 스캔된 이미지 주소)"""
  sourceFiles: [String!]

  """연결된 토픽 ID 목록"""
  topicIds: [ID!]
}

type BookInBucket {
  key: String!
  lastModified: String
  size: Int
  signedUrl: String
}

extend type Query {
  """ID로 책 1권 조회"""
  getBookById(id: ID!): Book

  """특정 토픽 ID로 연결된 책 목록 조회"""
  getBooksByTopic(topicId: ID!): [Book!]!

  """특정 태그로 연결된 책 목록 조회 (페이징 지원)"""
  findBooksInBucket(prefix: String): [BookInBucket!]!
}

extend type Mutation {
  """책 생성"""
  createBook(input: CreateBookInput!): Book

  """책 수정"""
  updateBook(input: UpdateBookInput!): Book

  """책 삭제"""
  deleteBook(id: ID!): Boolean
}